### ISSUE TITLE
Roadmap to version 1.0

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1234]
Kinda feels like we're getting closer to a version 1.0 release, although I don't think we need to put a time frame on it. Is it worth discussing which major development milestones we think should be part of v1.0?

Since we're following [SemVer](https://semver.org/) I guess it's not really about which features we want to see in v1.0 but more about whether we think the user interface will be relatively stable. New features could be introduced in v1.1, v1.2, etc. but if we make any breaking changes we'll have to release v2.0.

Maybe it's still useful to list some major milestones as they're quite likely to introduce breaking changes?

I'll start with the three big ones on my mind:
- [x] Pressure solvers for all topologies and grids (#586)
- [x] MPI distributed parallelism (#590) [not necessarily super optimized, just something that works okay]
- [x] Vertically stretched grid (#471)
- [ ]  Abstraction for vectors. It's only for simple grids that we can really get away with referring to the velocity field component wise with `u, v, w`.
- [ ] Specifying `architecture` when building `grid` (#1825).
- [ ] Simplify grids. We really only need one `RectilinearGrid`, one `LatitudeLongitudeGrid`, and one "arbitrary" (not aligned with a coordinate system, like what's used for the cubed sphere)
- [ ] Finalize spherical implementations
- [ ] Finalize bathymetry

Would be great to hear what people think and if anyone has any thoughts on v1.0.

Might also be good to include @whitleyv's immersed boundary implementation and @francispoulin's shallow water model since both might bring some breaking changes as well.

PS: Stuff added on 2021-07-23.

**Comment by navidcy** [comment]
pressure solver for all topologies -> definitely
MPI -> yeah, I think that's needed also
vertically stretched grid -> good feature but not a deal breaker for v1.0 in my opinion

**Comment by francispoulin** [comment]
I agree with @navidcy on all counts.  Will add that I hope to have Shallow water model together by early next week.  Not needed for 1.0 but I am happy to get it done before 1.0, if possible.

**Comment by ali-ramadhan** [comment]
Ah I don't see us tagging v1.0 for at least a few, probably even several, months so early next week is way ahead of v1.0 haha.

**Comment by glwagner** [comment]
I'd vote for resolving #1168 and #963 before releasing a 1.0, and also some usability issues like #890 .

#1175 is also breaking.

Something to consider: vertically-stretched grids may require specifying the `architecture` in `grid`, rather than `model`... ? This would be a substantial change to the API. So one motivation for requiring a vertically stretched grid implementation for 1.0 would be so that we don't have to "anticipate" breaking changes that the stretched grid requires.

I'm slightly concerned about boundary conditions too (in principle, we should be able to coalesce `TracerBoundaryConditions`, `UVelocityBoundaryConditions` into a single `FieldBoundaryConditions` specifier). But because it's not super high priority we haven't found time to attend to that and maybe it doesn't matter for 1.0.

**Comment by navidcy** [comment]
#1168 is resolved! no?

**Comment by glwagner** [comment]
Ahh I meant #1138. Ha!

**Comment by navidcy** [comment]
ok, makes much more sense :)

**Comment by tomchor** [comment]
I just thought I'd drop by with my point of view as user and (for now) not a developer. Talking with other people who have tried Oceananigans, the most important thing from our point of view may be the MPI parallelism. I know there is some debate to be had in this topic (I've had a couple discussions with @glwagner myself), but for now my understanding is that it's much easier to have access to CPUs then GPUs. Also if I understand correctly that would allow the model to be run on multiple GPUs, which will allow for some really big simulations resolving a huge array of scales. I bet there's new physics to be found there among the nonlinear interactions between all these scales!

From my point of view (now without talking to other users) #1241 seems like a pretty big issue. It's hard to use Oceananigans if you're not sure you're going to be able to calculate the statistics you need to do your science, which would force you to rely on instantaneous snapshots. For what I want right now it seems like I can use `LESbrary.jl`, but that might not always be the case. I'd definitely put that in the list of issues to be resolved asap.

From a user perspective I think #890 is also important. I've suffered the consequences of lack of attention to BCs already and it'd be nice to have the model check those for me.

I also think #471 would be nice to have. I agree with @navidcy that it's not a deal breaker, but it would save computation and (if I understand correctly) all the hard work for that has been done already, no?

Anyway, I'm still learning about Oceananigans and might be kind of naive in relation to some of the model's particularities. So please that fact into consideration when assessing my suggestions! 

Cheers

**Comment by glwagner** [comment]
> It's hard to use Oceananigans if you're not sure you're going to be able to calculate the statistics you need to do your science straightforwardly. For what I want right now it seems like I can use LESbrary.jl, but that might not always be the case.

If we did not have AbstractOperations at all, then isn't Oceananigans still better off than existing codes? I'd argue that even without AbstractOperations, users are still in decent shape for complicated diagnostics compared to other codes, since they can write their diagnostics code in julia (rather than some other language...)

But perhaps I'm missing something? What special diagnostics features are available in other LES codes? Why is writing a kernel using julia code less straightforward than what you'd have to do in another code?

**Comment by glwagner** [comment]
I guess I agree that it'd be really nice to solve #1241... I've beat my head against the wall for quite a while on that problem.

One solution is to invest more effort in trying to resolve it. Another possibility is to make the "backup plan" a bit easier (developing custom fields for complicated output). Since it's unlikely AbstractOperations will meet *all* of users diagnostics needs anyways (considering the possibilty of weird / computationally intensive diagnostics...) I think this is a worthwhile investment anyways. 

@tomchor perhaps including some examples about how to develop custom diagnostics kernels in your own scripts will be useful, so that you don't feel like you are out of luck unless you have something like the LESbrary? What do you think?

**Comment by glwagner** [comment]
#1245 might need to be addressed to, since its solution might lead to breaking changes.

**Comment by tomchor** [comment]
Basically, from the docs, I thought the only way to calculate statistics with Oceananigans was to use abstract operations. I have recently found that you can also write kernels, so I guess my comment on that part is invalid.

**Comment by tomchor** [comment]
All the checkboxes are ticked for this issue. Should we close it? Maybe create another one for v1.0 since apparently [there are many more things until v1.0](https://github.com/CliMA/Oceananigans.jl/issues/1620#issuecomment-882109635)?

**Comment by navidcy** [comment]
Or modify it to add more checkboxes to be checked in when ready?

**Comment by tomchor** [comment]
Added it to the main post.

Also, just my personal opinion: I think it would be great to have all those features/modifications ready, but I think there's also a big advantage in having a v1.0 relatively soon. The code is mature enough to write scientific papers with at this point (IMO), but not having a v1.0 might give out a impression that the code is "half-baked" or something, making some people reluctant accept it as a "serious code".

v1.0 isn't gonna be the last version we ever release, so I think it's okay to release a v1 with a subset of these features and push the other items to a v2.0 that might come out afterwards.

**Comment by glwagner** [comment]
> The code is mature enough to write scientific papers with at this point (IMO)

👀 

> but not having a v1.0 might give out a impression that the code is "half-baked" or something, making some people reluctant accept it as a "serious code".

I don't agree with this statement. Many extant codes don't use versioning at all. I would argue that people who make those judgements aren't "serious people", and it's their problem, not ours.

I think the purpose of versioning is to communicate to users and developers about bug fixes and API changes, and we should stick to that when motivating our decisions.

**Comment by glwagner** [comment]
> v1.0 isn't gonna be the last version we ever release, so I think it's okay to release a v1 with a subset of these features and push the other items to a v2.0 that might come out afterwards.

I agree with this. But the API is changing week by week, and not just small changes either...

**Comment by tomchor** [comment]
> I think the purpose of versioning is to communicate to users and developers about bug fixes and API changes, and we should stick to that when motivating our decisions.

I pretty much agree with @glwagner, and I'm not arguing against that. Just to be clear, I never said not to follow SemVer. I'm also not advocating to release v1.0 _now_. I'm just saying I see a reason to tag v1 before all the items in the wishlist are done.

**Comment by ali-ramadhan** [comment]
I feel like this issue has become stale and should maybe be closed?

At least when this issue was first opened we thought (at least I thought) v1.0 would only include one model on one grid so it was easy to come up with a short checklist/roadmap to v1.0.

But now with more models and grids (a great thing!) the API will probably be unstable for a long time (not a bad thing) so a v1.0 may not be close enough for a short checklist?

If people are interested in maintaining a roadmap we could go the long checklist route as @navidcy suggests: https://github.com/JuliaData/DataFrames.jl/issues/1678 and https://github.com/FluxML/Flux.jl/issues/1431 might be inspirations.

I for one wouldn't mind seeing v0.100.

**Comment by glwagner** [comment]
This discussion is stale; we aren't ready for 1.0, so we'll have to start the discussion again when we're ready.

**Comment by taimoorsohail** [comment]
Are we ready now?

**Comment by navidcy** [comment]
> I for one wouldn't mind seeing v0.100.

We definitely reached that 😆

**Comment by ali-ramadhan** [comment]
> Are we ready now?

I'll let others chime in but considering the current rate of breaking changes it feels like the public API will continue to change for the forseeable future. This is a good thing as it means it's being continuously improved upon, but maybe it's a sign that Oceananigans is not ready for v1.0?

It might be possible to come up with an evolving list of action items we want done before tagging and releasing v1.0. If it's a goal we feel is worth tracking.

From a scientist's point of view, I'm not sure if v1.0 says much. Presumably most scientists/users aren't familiar with semantic versioning. I think most scientists would rather rely on word of mouth and existing publications to decide whether to use Oceananigans or not. I don't think v1.0 means necessarily means ready-to-use and it definitely does not mean bug-free, it just means stable API and that your script won't break until at least the next major version.

I feel like there are certain changes, e.g. changing how a particular advection scheme works, that would not change the public API at all so would not technically be a breaking change but could significantly change the output of a simulation. I guess I would classify this as a "scientific breaking change" haha. So maybe it would be good to minimize these kinds of changes post v1.0.
