### ISSUE TITLE
Simple tests for correct halo filling + dynamics with the MultiRegion cubed sphere

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3020]
Starting proposal for tasks that ensure the cubed sphere halo filling and dynamics are correct:

- [ ] Advect a Gaussian bump over the sphere, show correctness of the solution and tracer conservation.
- [ ] Test that the velocity halos are correct by direct inspection.
- [ ] Test that vorticity can be computed (also at corners), recover analytical solution
- [ ] Shallow water tests: Rossby-Haurwitz, Gaussian splash

```[tasklist]
### Tasks
- [ ] Advect a Gaussian bump over the sphere, show correctness of the solution and tracer conservation.
- [ ] Test that the velocity halos are correct by direct inspection.
- [ ] Test that vorticity can be computed (also at corners), recover analytical solution
- [ ] Shallow water tests: Rossby-Haurwitz, Gaussian splash
```

**Comment by glwagner** [comment]
How about we put together one PR to solve

>  Advect a Gaussian bump over the sphere, show correctness of the solution and tracer conservation.

and a second PR to resolve the other three tasks on this issue?

@siddharthabishnu @navidcy
